// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// splitConditional
Rcpp::List splitConditional(NumericVector zcut, NumericMatrix zcutCat, List datMatrix, List parameters);
RcppExport SEXP _mvITR_splitConditional(SEXP zcutSEXP, SEXP zcutCatSEXP, SEXP datMatrixSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type zcut(zcutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type zcutCat(zcutCatSEXP);
    Rcpp::traits::input_parameter< List >::type datMatrix(datMatrixSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(splitConditional(zcut, zcutCat, datMatrix, parameters));
    return rcpp_result_gen;
END_RCPP
}
// splitContinuous
Rcpp::List splitContinuous(NumericVector zcut, NumericMatrix zcutCat, List datMatrix, List parameters);
RcppExport SEXP _mvITR_splitContinuous(SEXP zcutSEXP, SEXP zcutCatSEXP, SEXP datMatrixSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type zcut(zcutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type zcutCat(zcutCatSEXP);
    Rcpp::traits::input_parameter< List >::type datMatrix(datMatrixSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(splitContinuous(zcut, zcutCat, datMatrix, parameters));
    return rcpp_result_gen;
END_RCPP
}
// splitSurvival
Rcpp::List splitSurvival(NumericVector zcut, NumericMatrix zcutCat, List datMatrix, List parameters);
RcppExport SEXP _mvITR_splitSurvival(SEXP zcutSEXP, SEXP zcutCatSEXP, SEXP datMatrixSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type zcut(zcutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type zcutCat(zcutCatSEXP);
    Rcpp::traits::input_parameter< List >::type datMatrix(datMatrixSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(splitSurvival(zcut, zcutCat, datMatrix, parameters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvITR_splitConditional", (DL_FUNC) &_mvITR_splitConditional, 4},
    {"_mvITR_splitContinuous", (DL_FUNC) &_mvITR_splitContinuous, 4},
    {"_mvITR_splitSurvival", (DL_FUNC) &_mvITR_splitSurvival, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvITR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
