# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splitConditional <- function(zcut, zcutCat, datMatrix, parameters) {
    .Call('_mvITR_splitConditional', PACKAGE = 'mvITR', zcut, zcutCat, datMatrix, parameters)
}

splitContinuous <- function(zcut, zcutCat, datMatrix, parameters) {
    .Call('_mvITR_splitContinuous', PACKAGE = 'mvITR', zcut, zcutCat, datMatrix, parameters)
}

splitSurvival <- function(zcut, zcutCat, datMatrix, parameters) {
    .Call('_mvITR_splitSurvival', PACKAGE = 'mvITR', zcut, zcutCat, datMatrix, parameters)
}

